image: python:3.12.4

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  FLASK_APP: app.py
  FLASK_ENV: production
  FLASK_RUN_HOST: 0.0.0.0
  FLASK_RUN_PORT: 5000

cache:
  paths:
    - .venv/

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Building application..."

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - docker build -t my-flask-app .
    - docker run -d -p 5000:5000 my-flask-app
  only:
    - master
